### ISSUE TITLE
Structure wrong of the reposetory. unable to add to hacs

### ISSUE THREAD

**Issue by Coffee0297** [ricreis394/chartjs-card#10]
Think this says it all:

![image](https://user-images.githubusercontent.com/43273303/167640887-dde40bde-0257-400f-9063-517e19fe825d.png)

**Comment by plckr** [comment]
Unfortunatly I'm very away from Home Assistant, so this error isn't much obvious for me
Can you confirm you are adding it correctly? Any guess what it could be?
At first I thought maybe was the structure of `hacs.json` but looking for HACS documentation, all seems correct
