### ISSUE TITLE
Regex template check precludes using functions in callbacks

### ISSUE THREAD

**Issue by andrewdolphin** [ricreis394/chartjs-card#2]
Firstly, thanks for this card - extremely flexible for charting custom data.

I've found that the regex template used to evaluate templates (**^\${([^}]+)}$**) doesn't allow for defining functions within, for example, a callback as the grouping function excludes templates that contain "}". I think this test is superfluous given the template already test for an ending "}".

By updating the regex template to **^\${(.+)}$** the callback functions pass and can be used for more in depth customisation. For example, to format Y axis labels to include a unit:

```options:
  scales:
    yAxes:
      - id: 'first_y'
        type: linear
        ticks:
          callback: "${(function callback(value, index, values) {return value + 'm';})}"
```

**Comment by plckr** [comment]
Hello, thanks for reporting.
I fixed the regex template issue https://github.com/ricreis394/chartjs-card/commit/efc203eb3ceae8b6ad24ba54ef58eee4cd6cb76d, but I don't think function calls will be possible
Can you please test?

**Comment by andrewdolphin** [comment]
My example above is a working example on a version of chartjs modified by myself so yes it definitely works! There is a quirk needed to get eval() to return a function; note the need to define the function with a name and surround the entire function definition with brackets.

**Comment by andrewdolphin** [comment]
The benefits aren't limited to just callbacks either, the following is an example of returning an array of the correct length to override styling for a dataset, in this example setting the pointhitradius to zero for 3 out of 4 points in a scatter chart.
```
          datasets:
            - data: '${states["sensor.tides"].attributes.values}'
              borderColor: var(--mdc-theme-primary)
              showLine: true
              pointHitRadius: '${ var z = (states["sensor.tides"].attributes.values).length;
                                  let a = new Array(z); for (let i=0; i<z; ++i) {a[i] = (i % 4 === 0) * 5;}
                                  a;}'
              borderWidth: 5
```

**Comment by andrewdolphin** [comment]
Fixed in https://github.com/ricreis394/chartjs-card/commit/efc203eb3ceae8b6ad24ba54ef58eee4cd6cb76d
